title: [Meeting minutes] [2025-01-00] 회의록

body:
  - type: markdown
    attributes:
      value: |
        ## Agenda
        - [논의할 주요 주제]

        ## 진행 상황 공유
        - **완료된 작업**:
          - [작업 내용]
        - **현재 진행 중인 작업**:
          - [작업 내용]

        ## TODO (앞으로 해야 할 작업)
        - [작업 내용 및 담당자]
